services:
  api:
    build: .
    ports:
      - "8000:8000"

  mlflow-ui:
    build: .
    command:
      [
        "mlflow", "ui",
        "--backend-store-uri", "sqlite:////app/mlflow_store/mlflow.db",
        "--default-artifact-root", "/app/mlruns",
        "--host", "0.0.0.0",
        "--port", "5000",
      ]
    ports:
      - "5000:5000"
